import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RobotProvider } from "../context/RobotContext";
import Navbar from "../components/Navbar";
// import RodNavbar from "../components/RodNavbar";
import Sidebar from "../components/Sidebar";
import SmoothScrolling from "../components/SmoothScrolling";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
        suppressHydrationWarning={true}
      >
        <RobotProvider>
          <SmoothScrolling />

          <Sidebar />
          <div className="lg:pl-14 transition-all duration-300">
            {children}
          </div>
        </RobotProvider>
      </body>
    </html>
  );
}
